# 自动化名称
name: Deploy Yuque-Hexo Public To Pages

# 当有语雀推送时触发action
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: main
    paths:
      -'source/_posts/*'  # 只会在_posts更改时触发

# 设置环境
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}

    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      # from: https://github.com/actions/setup-node
      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: 安装Hexo
        run: |
          npm install hexo-cli -g
          yuque-hexo clean
          yuque-hexo sync


      - name: 设置Git信息
        run: |
          git config --global user.name 'wyblog'
          git config --global user.email '3227988255@qq.com'

      - name: 更新 语雀拉取缓存及文章 #更新yuque 拉取的文章到GitHub仓库
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
          git config --global user.email "3227988255@qq.com"
          git config --global user.name "wyblog"
          git add .
          git commit -m "Refresh yuque json" -a
      - name: 推送 语雀拉取缓存及文章 #推送修改后的yuque json
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}

      - name: 缓存 Hexo
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
